version: '3.8'

services:
  db:
    image: mariadb:10.4
    container_name: mariadb_municipalidad
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password_seguro
      MYSQL_DATABASE: municipalidad_yau
      MYSQL_USER: user_backend
      MYSQL_PASSWORD: password_backend_123
    ports:
      - "3306:3306"
    volumes:
      - ./DataBase/db.sql:/docker-entrypoint-initdb.d/db.sql
      # Volumen para que tus datos de prueba no se borren al apagar el contenedor
      - mariadb_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_municipalidad
    restart: always
    profiles:
      - fullstack
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=user_backend
      - DB_PASSWORD=password_backend_123
      - DB_NAME=municipalidad_yau
      - DB_CONNECTION_LIMIT=10
      - JWT_SECRET=super_secret_key_jwt_2026_municipalidad
      - JWT_EXPIRES_IN=8h
      - PORT=3000
    depends_on:
      - db

volumes:
  mariadb_data:
